development:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: lobster_dev
  socket: /tmp/mysql.sock
  username: lobster
  password: lobster

production: 
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: <%= ENV["MYSQLDATABASE"] %>
  host: <%= ENV["MYSQLHOST"] %>
  port: <%= ENV["MYSQLPORT"] %>
  username: <%= ENV["MYSQLUSER"] %>
  password: <%= ENV["MYSQLPASSWORD"] %>
