production: 
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: <%= ENV["MYSQLDATABASE"] %>
  host: <%= ENV["MYSQLHOST"] %>
  port: <%= ENV["MYSQLPORT"] %>
  username: <%= ENV["MYSQLUSER"] %>
  password: <%= ENV["MYSQLPASSWORD"] %>
  
